a=int(input("Digite um valor inteiro:"))
b=int(input("Digite um valor inteiro:"))
c=int(input("Digite um valor inteiro:"))
d=int(input("Digite um valor inteiro:"))
diferença=(a*b-c*d)
print("A diferença da soma de a+b e c+d é:",diferença)
